blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://code.hannahvernon.com/hannah-vernon/GmsaScheduledTaskTools#readme
    about: Read the README for usage, requirements, and examples.
